// Command docgen writes the generated permission and scope reference pages.
//
// docs/README.md's generated-pages table: "reference/permissions.md, reference/scopes.md" are
// generated from "internal/authz/catalogue.go", in phase 2. Canonical §6 says the same from the other
// end — the catalogue "generates the permission table seed, the OpenAPI x-dkp-permission metadata,
// the PAT scope enum, the authorization-matrix header, and docs/reference/permissions.md". This is
// the last clause, and the ROADMAP's phase-2 exit criterion states it as a requirement:
// "docs/reference/permissions.md is generated, not written."
//
// A GENERATOR, NOT A GATE. It rewrites and says nothing; the drift assertion is `make
// verify-generated`, which hashes docs/reference, regenerates and hashes again. Keeping the two apart
// is what lets `make gen` be the fix rather than another thing to interpret — the same division
// internal/ledger/enumgen documents.
//
// IT RUNS LAST IN `make gen`, AND UNLIKE enumgen IT MAY. enumgen is first and must compile without
// generated code, because a tree whose sqlc output does not build has to be able to repair itself.
// This one imports internal/authz, which reaches internal/store/sqlitegen through the boot
// reconciliation, so it must run AFTER sqlc — and it can, because nothing it writes is an input to
// any other generator.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/prokopto-dev/dragonkillparty/internal/authz"
)

// The two pages this command owns, relative to the repo root, which is where `make gen` runs its
// scripts from.
const (
	defaultDir      = "docs/reference"
	permissionsFile = "permissions.md"
	scopesFile      = "scopes.md"
)

// generatedBanner is the first line of every page. It is HTML rather than a Markdown heading so it
// renders as nothing, and it names the command that rewrites the file — an agent who opens the page
// to fix a typo needs to be told where the typo actually lives before they edit a file `make gen`
// will overwrite.
const generatedBanner = "<!-- GENERATED by `make gen` from internal/authz/catalogue.go. " +
	"Edit the catalogue, not this file. -->"

func main() {
	dir := defaultDir
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}

	if err := run(dir); err != nil {
		fmt.Fprintf(os.Stderr, "docgen: %v\n", err)
		os.Exit(1)
	}
}

// run writes both pages into dir, creating it if it does not exist.
func run(dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", dir, err)
	}

	pages := map[string]func() string{
		permissionsFile: permissionsPage,
		scopesFile:      scopesPage,
	}

	for _, name := range sortedKeys(pages) {
		if err := writeIfChanged(filepath.Join(dir, name), pages[name]()); err != nil {
			return err
		}
	}

	return nil
}

// writeIfChanged writes content to path only when the bytes differ.
//
// The skip matters for the same reason enumgen's does: `make gen` runs reflexively, and a generator
// that rewrites a committed file on every invocation makes every `make` in the repository look like
// the docs had moved. Written through a temp file and a rename so an interrupted run cannot leave a
// truncated page behind.
func writeIfChanged(path, content string) error {
	if existing, err := os.ReadFile(path); err == nil && string(existing) == content {
		return nil
	}

	tmp, err := os.CreateTemp(filepath.Dir(path), filepath.Base(path)+".docgen-*")
	if err != nil {
		return fmt.Errorf("create temp file for %s: %w", path, err)
	}

	tmpName := tmp.Name()

	defer func() { _ = os.Remove(tmpName) }()

	if _, err := tmp.WriteString(content); err != nil {
		_ = tmp.Close()

		return fmt.Errorf("write %s: %w", tmpName, err)
	}

	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close %s: %w", tmpName, err)
	}

	// 0644: the pages are committed and read by everyone. mktemp-style files are 0600, and leaving a
	// generated, committed file readable only by whoever ran `make gen` is a surprise waiting in a
	// container build — the same reasoning scripts/gen-openapi.sh records.
	if err := os.Chmod(tmpName, 0o644); err != nil {
		return fmt.Errorf("chmod %s: %w", tmpName, err)
	}

	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("rename %s to %s: %w", tmpName, path, err)
	}

	return nil
}

// permissionsPage renders docs/reference/permissions.md.
//
// GROUPED BY CATEGORY, in first-appearance order, which is canonical §6's order — the catalogue's
// SortOrder follows the same list, so the page reads down the same sequence the role editor renders
// across. Nothing here re-sorts alphabetically: §6 groups related keys together deliberately, and
// alphabetising would scatter `raid.tick.create` away from `raid.create`.
func permissionsPage() string {
	catalogue := authz.Catalogue()

	var b strings.Builder

	b.WriteString(generatedBanner + "\n\n")
	b.WriteString("# Permissions\n\n")
	// Directly under the heading, before anything describing a control. A disclosure a reader
	// reaches last is one they reach after believing the page.
	b.WriteString("> " + authz.Phase0EnforcementNotice + "\n\n")
	fmt.Fprintf(&b,
		"The %d permission keys a role can grant. They are `<resource>.<action>`, dot-separated and\n"+
			"lowercase, and this page is generated from `internal/authz/catalogue.go` — the single source\n"+
			"([canonical §6](../design/00-canonical-conventions.md)). The same catalogue is reconciled\n"+
			"into the `permission` table at every boot, so a key here is a key the database has a row\n"+
			"for.\n\n", len(catalogue))
	b.WriteString("Two values appear in an operation's permission column and are **not** keys here:\n" +
		"`public` (no credential required) and `self` (any authenticated principal, constrained to its\n" +
		"own records).\n\n")
	b.WriteString("A **step-up** key is in [the capability floor](#the-capability-floor): session-only,\n" +
		"no PAT scope, and a recent re-authentication. A **dangerous** key is one the role editor\n" +
		"confirms twice before granting — an affordance, not a control.\n\n")

	for _, category := range categoriesInOrder(catalogue) {
		b.WriteString("## " + heading(category) + "\n\n")
		b.WriteString("| Key | Label | Flags | Description |\n")
		b.WriteString("|---|---|---|---|\n")

		for _, p := range catalogue {
			if p.Category != category {
				continue
			}

			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", p.Key, p.Label, flags(p), p.Description)
		}

		b.WriteString("\n")
	}

	b.WriteString("## The capability floor\n\n")
	b.WriteString("These keys alter authentication, authorization or bulk-export state. Operations that\n" +
		"require one are **session and step-up only** and carry no PAT scope at all — there is no\n" +
		"`admin:*` scope and no all-powerful token ([ADR-0011](../adr/0011-opaque-pats-no-superadmin-token.md)).\n" +
		"Holding one is an ordinary role grant; exercising it needs a re-authenticated browser session.\n\n")

	for _, key := range authz.CapabilityFloor() {
		fmt.Fprintf(&b, "- `%s`\n", key)
	}

	b.WriteString("\n`admin.owner` is in that list and is an **ordinary permission row**, not a hardcoded\n" +
		"superuser branch. Revoking it is an ordinary role change, and at least one account must hold it.\n")

	return b.String()
}

// scopesPage renders docs/reference/scopes.md.
func scopesPage() string {
	scopes := authz.Scopes()

	var b strings.Builder

	b.WriteString(generatedBanner + "\n\n")
	b.WriteString("# PAT scopes\n\n")
	b.WriteString("> " + authz.Phase0EnforcementNotice + "\n\n")
	fmt.Fprintf(&b,
		"The %d scopes a personal access token can carry. They are `<family>:<verb>`,\n"+
			"colon-separated, and this page is generated from `internal/authz/catalogue.go`\n"+
			"([canonical §6](../design/00-canonical-conventions.md)). The same list is published in the\n"+
			"OpenAPI document as `x-dkp-scopes` on the `pat` security scheme.\n\n", len(scopes))
	b.WriteString("**Scopes are coarser than [permissions](permissions.md) on purpose:** a scope narrows a\n" +
		"token, a permission narrows a role. Effective capability is the intersection —\n" +
		"`role permissions ∩ token scopes` — so a token can only ever narrow what its service account\n" +
		"already has, and a scope on a token whose account lacks the matching permission grants\n" +
		"nothing.\n\n")

	b.WriteString("| Scope | Label | Description |\n")
	b.WriteString("|---|---|---|\n")

	for _, s := range scopes {
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", s.Key, s.Label, s.Description)
	}

	b.WriteString("\n## What no scope covers\n\n")
	b.WriteString("Operations that alter authentication, authorization or bulk-export state have **no\n" +
		"scope at all** and are session-and-step-up only. See\n" +
		"[the capability floor](permissions.md#the-capability-floor) for the exact set of keys.\n")

	return b.String()
}

// flags renders a permission's policy flags for the table's Flags column.
//
// Empty for most keys, which is the point: one key is dangerous and nine are step-up, so a pair of
// dedicated columns would be blank in fifty-odd rows and the two facts worth noticing would be
// invisible in the whitespace.
func flags(p authz.Permission) string {
	var out []string

	if p.RequiresStepUp {
		out = append(out, "**step-up**")
	}

	if p.IsDangerous {
		out = append(out, "**dangerous**")
	}

	return strings.Join(out, ", ")
}

// categoriesInOrder returns each category once, in the order it first appears in the catalogue.
//
// First-appearance rather than sorted, so the page follows canonical §6 rather than the alphabet.
func categoriesInOrder(catalogue []authz.Permission) []string {
	seen := map[string]bool{}

	var out []string

	for _, p := range catalogue {
		if !seen[p.Category] {
			seen[p.Category] = true

			out = append(out, p.Category)
		}
	}

	return out
}

// heading renders a category as a section heading: the catalogue's own value with its first letter
// capitalised, never a lookup table. A category-to-heading map would be a second vocabulary to keep
// in step with the first, for the sake of prettier capitalisation.
func heading(category string) string {
	if category == "" {
		return category
	}

	return strings.ToUpper(category[:1]) + category[1:]
}

// sortedKeys exists so the map iteration in run() is deterministic where it matters. The two pages
// are written independently and neither reads the other, so ordering does not affect content — but a
// failure message that names a different file on every run is one nobody can reproduce.
func sortedKeys(m map[string]func() string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}

	sort.Strings(out)

	return out
}
