// The generated API client — the ONE sanctioned HTTP surface in the SPA (.claude/rules/web.md).
//
// schema.d.ts beside this file is generated by openapi-typescript from openapi/openapi.json
// (`pnpm run generate:client`). This module instantiates openapi-fetch against those types and
// bootstraps its base URL from the runtime /config.json. Everything else in web/src imports `api`
// from here and never touches fetch directly — eslint's no-restricted-globals and the WEB001 grep
// both exempt only web/src/api, which is this directory.
import createClient from "openapi-fetch";

import type { paths } from "./schema";

// The runtime configuration document served by internal/api/config_json.go. API_BASE is prepended to
// every request path, so the same built bundle can be pointed at any instance — the capability that
// proves the SPA is a client.
interface RuntimeConfig {
  API_BASE: string;
}

const CONFIG_URL = "/config.json";

// The client is created once with a mutable baseUrl that bootstrapClient sets from /config.json
// before the first render. It is exported so query/mutation modules import `api` and call
// api.GET(...) / api.POST(...).
export const api = createClient<paths>({ baseUrl: "" });

// bootstrapClient reads /config.json and points the client at API_BASE. It is the one place a raw
// fetch is allowed: it fetches the CLIENT's own base URL, so it cannot itself route through the
// client. main.tsx awaits it before rendering, so no query fires against the wrong origin.
export async function bootstrapClient(): Promise<void> {
  const base = await loadApiBase();
  // openapi-fetch does not expose a setter, so re-create with the resolved base. This runs exactly
  // once at boot; there is no per-request cost.
  Object.assign(api, createClient<paths>({ baseUrl: base }));
}

async function loadApiBase(): Promise<string> {
  try {
    const res = await fetch(CONFIG_URL, { headers: { Accept: "application/json" } });
    if (!res.ok) {
      return "";
    }
    const body = (await res.json()) as Partial<RuntimeConfig>;
    return typeof body.API_BASE === "string" ? body.API_BASE : "";
  } catch {
    // A missing /config.json means same-origin — the binary that served the SPA is where the API is.
    return "";
  }
}
