/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get server capabilities and build information
         * @description Returns the running binary's version, the API versions this instance serves, and the version of the OpenAPI contract it implements. Unauthenticated: a client needs this before it can decide how to authenticate.
         */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Placeholder webhook event
         * @description A no-op event that exists to prove the `webhooks` block round-trips through the spec pipeline. Replaced by the generated event catalogue; it is not emitted by any code and should not be subscribed to.
         */
        post: operations["webhookPing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        ErrorDetail: {
            /** @description A per-field reason code */
            code?: string;
            /** @description Where the error occurred, e.g. 'body.items[3].tags' */
            location?: string;
            /** @description Human-readable explanation of this one problem */
            message: string;
            /** @description Legal values or a corrected form, when they can be named */
            suggestions?: string[] | null;
        };
        MetaBody: {
            /** @description Versioned API prefixes this instance serves */
            api_versions: string[] | null;
            /** @description Build identity of the running binary */
            server: components["schemas"]["MetaServer"];
            /** @description Version of the OpenAPI contract this instance implements */
            spec_version: string;
        };
        MetaServer: {
            /** @description Build timestamp as stamped at link time, or "unknown" */
            built_at: string;
            /** @description Git commit the binary was built from, or "none" */
            commit: string;
            /** @description Release version, or "dev" for an unstamped build */
            version: string;
        };
        ProblemDetail: {
            /**
             * @description Stable machine-readable discriminator from a closed enum
             * @enum {string}
             */
            code: "unauthenticated" | "token_invalid" | "token_expired" | "token_revoked" | "token_in_query_string" | "session_required" | "step_up_required" | "insufficient_scope" | "permission_denied" | "not_found" | "method_not_allowed" | "unsupported_media_type" | "payload_too_large" | "validation_failed" | "unknown_field" | "invalid_filter" | "invalid_sort_field" | "invalid_expand" | "cursor_invalid" | "cursor_filter_mismatch" | "bad_request" | "idempotency_key_required" | "idempotency_key_reused" | "idempotency_key_in_flight" | "precondition_required" | "precondition_failed" | "conflict" | "unknown_character" | "unknown_item" | "ambiguous_item" | "artifact_unparseable" | "submission_stale" | "raid_finalized" | "invalid_field_value" | "insufficient_balance" | "invariant_violation" | "ledger_immutable" | "batch_already_reversed" | "pool_strategy_mismatch" | "pool_is_mirroring" | "session_state_invalid" | "session_closed" | "outbid" | "invalid_increment" | "hold_conflict" | "bid_not_permitted" | "sealed_bids_not_revealed" | "session_already_settled" | "resolution_failed" | "rate_limited" | "setup_required" | "engine_unsupported" | "service_unavailable" | "internal_error";
            /** @description Explanation specific to this occurrence */
            detail?: string;
            /** @description Per-field problems, populated for validation failures */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /** @description URI reference identifying this specific occurrence */
            instance?: string;
            /** @description Structured, code-specific context a client can act on */
            meta?: {
                [key: string]: unknown;
            };
            /** @description Correlation id, echoed in the X-Request-Id header */
            request_id?: string;
            /**
             * Format: int64
             * @description HTTP status code
             */
            status: number;
            /** @description Short, stable summary of the problem type */
            title: string;
            /**
             * Format: uri
             * @description URI reference to documentation for this error type
             */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    webhookPing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The event name.
                     * @enum {string}
                     */
                    event: "ping";
                    /**
                     * Format: date-time
                     * @description RFC 3339 timestamp, always UTC (canonical §2).
                     */
                    occurred_at: string;
                };
            };
        };
        responses: {
            /** @description The consumer accepted the event. Any 2xx is treated as success. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
