#!/usr/bin/env bash
# The client half of `make gen`: web/src/api/schema.d.ts, generated by openapi-typescript from
# openapi/openapi.json.
#
# Same direction as gen-openapi.sh: the client is DERIVED from the committed spec, never authored.
# The spec is itself derived from the Go handler types, so the chain is one source of truth end to
# end — a UI type that disagrees with a bot is impossible by construction. web/src/api/ is committed
# and diff-gated (Makefile GENERATED_PATHS), so a handler change that is not reflected here fails
# `make verify-generated`.
#
# A hard requirement, never soft-skipped once web/ is scaffolded, for the reason gen-openapi.sh
# gives: a `make gen` that exits 0 because a generator was missing reports a clean tree it never
# inspected. The one sanctioned skip is the pre-scaffold state where web/package.json does not exist.

set -euo pipefail

# Same DKP_REPO_ROOT contract as the other gen scripts; `make gen` strips it with `env -u`.
cd "${DKP_REPO_ROOT:-$(dirname "$0")/..}"

die() { printf '\033[31m  %s\033[0m\n' "$*" >&2; exit 1; }

# Pre-scaffold: no web project yet, nothing to generate. Disappears once web/package.json is
# committed (which is the human-gated manifest that lands the SPA dependency set).
if [ ! -f web/package.json ]; then
	printf '  web/ is not scaffolded — no client to generate\n'
	exit 0
fi

command -v pnpm >/dev/null 2>&1 || die "pnpm is not installed — see make setup"

# --frozen-lockfile --ignore-scripts: the same install posture CI and the build use. The generator
# is a devDependency, so it must be installed before it can run.
[ -d web/node_modules ] || (cd web && pnpm install --frozen-lockfile --ignore-scripts)

# openapi-typescript reads ../openapi/openapi.json and writes src/api/schema.d.ts — the script is
# defined as `generate:client` in web/package.json so the path is named once, there.
(cd web && pnpm run generate:client)

printf '  \033[32mweb/src/api/schema.d.ts regenerated\033[0m — from openapi/openapi.json\n'
