// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlitegen

import (
	"context"
)

const getAppUser = `-- name: GetAppUser :one

SELECT
    id, username, username_norm, email, email_norm, email_verified_at, display_name,
    timezone, locale, state, session_epoch, last_login_at, failed_logins, locked_until_at,
    mfa_totp_secret_enc, mfa_enrolled_at, mfa_required, deleted_at, created_at, updated_at
FROM app_user
WHERE id = ?
`

// GetAppUser reads one user row by id.
//
// ITS CALLER IS CreateSession, AND THE REASON IS THE EPOCH. A session records the
// app_user.session_epoch it was minted under, and the resolver requires the two to be equal - so a
// session created without reading the user's current epoch would be born stale on any account that
// has ever signed out everywhere, and would be refused by the very next request. The read and the
// insert run in ONE transaction, so a concurrent epoch bump either precedes the read (and the
// session is born dead, correctly) or follows the insert (and kills it, correctly).
//
// There is no GetAppUserByUsernameNorm yet: looking a user up by what they typed is the login
// endpoint's read, and it arrives with the endpoint, its rate limits and its uniform-response rules.
func (q *Queries) GetAppUser(ctx context.Context, id string) (AppUser, error) {
	row := q.db.QueryRowContext(ctx, getAppUser, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNorm,
		&i.Email,
		&i.EmailNorm,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.Timezone,
		&i.Locale,
		&i.State,
		&i.SessionEpoch,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LockedUntilAt,
		&i.MfaTotpSecretEnc,
		&i.MfaEnrolledAt,
		&i.MfaRequired,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :exec

INSERT INTO api_token (
    id, prefix, token_hash, service_account_id, name, scopes, pepper_kid, expires_at,
    last_used_at, last_used_ip, rate_limit_rpm, created_by, revoked_at, revoked_by,
    revoke_reason, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NULL, '', ?, ?, NULL, NULL, '', ?)
`

type InsertAPITokenParams struct {
	ID               string
	Prefix           string
	TokenHash        []byte
	ServiceAccountID string
	Name             string
	Scopes           string
	PepperKid        string
	ExpiresAt        *int64
	RateLimitRpm     int64
	CreatedBy        string
	CreatedAt        int64
}

// InsertAPIToken writes one PAT row. The plaintext secret is NEVER stored and never recoverable:
// token_hash is HMAC-SHA256(pepper, secret) and the caller has already discarded everything else.
// Its callers are the mint endpoint (a later wave) and the tests that prove the bearer path resolves
// what the minting primitive produces - which is the point of it existing before its endpoint does.
func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, insertAPIToken,
		arg.ID,
		arg.Prefix,
		arg.TokenHash,
		arg.ServiceAccountID,
		arg.Name,
		arg.Scopes,
		arg.PepperKid,
		arg.ExpiresAt,
		arg.RateLimitRpm,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertAppUser = `-- name: InsertAppUser :exec


INSERT INTO app_user (
    id, username, username_norm, email, email_norm, email_verified_at, display_name,
    timezone, locale, state, session_epoch, last_login_at, failed_logins, locked_until_at,
    mfa_totp_secret_enc, mfa_enrolled_at, mfa_required, deleted_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, NULL, ?, NULL, NULL, ?, 0, NULL, 0, NULL, NULL, NULL, 0, NULL, ?, ?)
`

type InsertAppUserParams struct {
	ID           string
	Username     string
	UsernameNorm string
	Email        *string
	EmailNorm    *string
	DisplayName  string
	State        string
	CreatedAt    int64
	UpdatedAt    int64
}

// Identity and credentials - the cookie-or-bearer resolution path and the rows it reads
// (docs/design/01-domain-model.md section 4, docs/design/03-security.md sections 3 and 6).
//
// Shapes follow db/RECIPES.md. Every statement that reaches SQLite in this project is generated from
// a file like this one: db.Query and db.Exec outside internal/store are grep-banned (gate SQL002),
// so the only way a new query enters the codebase is by being written here first and reviewed as
// SQL.
//
// TWO RESOLVES, ONE PER CREDENTIAL CLASS, AND BOTH ARE ONE INDEXED LOOKUP. That is the hot path of
// every authenticated request: a cookie resolves by the SHA-256 of its secret against
// ux_session_token, and a bearer resolves by its public 8-character prefix against
// ux_api_token_prefix followed by one constant-time compare in Go. ADR-0011 accepted a database
// round trip per request as the price of instant revocation; it is one round trip, not a scan.
//
// NEITHER RESOLVE FILTERS ON expires_at OR revoked_at, and that is deliberate. The row comes back
// whole and internal/auth decides, because the middleware has to tell "no such credential" from
// "expired" from "revoked" from "the account is disabled" in its LOGS while returning the same 401
// to the caller either way. A WHERE clause that hid the row would leave the server unable to answer
// the only question that matters during an incident: was this token used, and when.
//
// NO DELETE STATEMENTS. A session or a token is revoked, never removed: "did the leaked token do
// anything" is answered from the row, and deleting it deletes the answer.
//
// THE TWO REVOKES SHIP AHEAD OF THEIR ENDPOINTS, and that is a deliberate exception to "a mutation
// with no caller is a method the Postgres target implements for nothing". The resolver has a branch
// for each - a revoked session and a revoked token are both refused - and a branch nobody has
// watched go red is a branch nobody knows works. Producing a revoked row is the only way to test
// them, and a test that fabricated one by writing the column through some other insert would be
// testing its own fixture. ADR-0011 sells instant revocation as the reason PATs are not JWTs; this
// is the statement that claim rests on, and it is one UPDATE on a row the auth path already reads.
// Sign-out and token revoke (session-and-step-up operations, canonical section 6) call these
// verbatim when they land.
//
// Keep this comment ASCII-only. sqlc v1.31.1 computes each query's text span in bytes but truncates
// by rune count, so a multibyte character (an em dash, a section sign) in a preceding comment lops
// that many trailing characters off the generated query string. The failure is silent at generate
// time and shows up as a syntax error only when the query runs.
// InsertAppUser writes one human login. The caller normalises username_norm and email_norm in Go
// (NFKC + casefold + strip ' ` -): core SQLite has no NFKC and lower() is ASCII-only, so a
// normalisation done in SQL would let a homoglyph of an officer's name be a second account that
// looks identical in every list.
func (q *Queries) InsertAppUser(ctx context.Context, arg InsertAppUserParams) error {
	_, err := q.db.ExecContext(ctx, insertAppUser,
		arg.ID,
		arg.Username,
		arg.UsernameNorm,
		arg.Email,
		arg.EmailNorm,
		arg.DisplayName,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertServiceAccount = `-- name: InsertServiceAccount :exec
INSERT INTO service_account (
    id, name, name_norm, description, owner_user_id, state, created_by, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertServiceAccountParams struct {
	ID          string
	Name        string
	NameNorm    string
	Description string
	OwnerUserID string
	State       string
	CreatedBy   string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) InsertServiceAccount(ctx context.Context, arg InsertServiceAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertServiceAccount,
		arg.ID,
		arg.Name,
		arg.NameNorm,
		arg.Description,
		arg.OwnerUserID,
		arg.State,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO session (
    id, user_id, token_hash, identity_id, session_epoch, created_at, last_seen_at,
    expires_at, absolute_expires_at, revoked_at, ip, user_agent, mfa_satisfied_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, ?, ?)
`

type InsertSessionParams struct {
	ID                string
	UserID            string
	TokenHash         []byte
	IdentityID        *string
	SessionEpoch      int64
	CreatedAt         int64
	LastSeenAt        int64
	ExpiresAt         int64
	AbsoluteExpiresAt int64
	Ip                string
	UserAgent         string
	MfaSatisfiedAt    *int64
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.IdentityID,
		arg.SessionEpoch,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.Ip,
		arg.UserAgent,
		arg.MfaSatisfiedAt,
	)
	return err
}

const insertUserIdentity = `-- name: InsertUserIdentity :exec

INSERT INTO user_identity (
    id, user_id, provider, provider_key, subject, password_hash, password_algo, password_set_at,
    must_reset, access_token_enc, refresh_token_enc, token_expires_at, scopes, profile_json,
    last_used_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, NULL, NULL, '', '{}', NULL, ?, ?)
`

type InsertUserIdentityParams struct {
	ID            string
	UserID        string
	Provider      string
	ProviderKey   string
	Subject       string
	PasswordHash  *string
	PasswordAlgo  *string
	PasswordSetAt *int64
	MustReset     int64
	CreatedAt     int64
	UpdatedAt     int64
}

// InsertUserIdentity writes one credential for a user. password_hash is the argon2id PHC string
// internal/auth produces; NULL means this identity cannot authenticate with a password, which is
// what the EQdkp importer writes because legacy hashes are never migrated.
func (q *Queries) InsertUserIdentity(ctx context.Context, arg InsertUserIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertUserIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderKey,
		arg.Subject,
		arg.PasswordHash,
		arg.PasswordAlgo,
		arg.PasswordSetAt,
		arg.MustReset,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const resolveAPIToken = `-- name: ResolveAPIToken :one

SELECT
    t.id, t.prefix, t.token_hash, t.service_account_id, t.name, t.scopes, t.pepper_kid, t.expires_at, t.last_used_at, t.last_used_ip, t.rate_limit_rpm, t.created_by, t.revoked_at, t.revoked_by, t.revoke_reason, t.created_at,
    a.state AS service_account_state,
    a.owner_user_id AS owner_user_id,
    a.name AS service_account_name
FROM api_token t
JOIN service_account a ON a.id = t.service_account_id
WHERE t.prefix = ?
`

type ResolveAPITokenRow struct {
	ApiToken            ApiToken
	ServiceAccountState string
	OwnerUserID         string
	ServiceAccountName  string
}

// ResolveAPIToken is the bearer half: one lookup on the PUBLIC prefix, joined to the service account
// for its state and its human owner.
//
// IT RETURNS token_hash, and the comparison is a constant-time one in Go. Comparing in SQL would be
// a byte-by-byte comparison whose timing is observable, and matching on the hash instead of the
// prefix would move the secret into the query - and into every statement log and slow-query trace
// that ever reads one.
func (q *Queries) ResolveAPIToken(ctx context.Context, prefix string) (ResolveAPITokenRow, error) {
	row := q.db.QueryRowContext(ctx, resolveAPIToken, prefix)
	var i ResolveAPITokenRow
	err := row.Scan(
		&i.ApiToken.ID,
		&i.ApiToken.Prefix,
		&i.ApiToken.TokenHash,
		&i.ApiToken.ServiceAccountID,
		&i.ApiToken.Name,
		&i.ApiToken.Scopes,
		&i.ApiToken.PepperKid,
		&i.ApiToken.ExpiresAt,
		&i.ApiToken.LastUsedAt,
		&i.ApiToken.LastUsedIp,
		&i.ApiToken.RateLimitRpm,
		&i.ApiToken.CreatedBy,
		&i.ApiToken.RevokedAt,
		&i.ApiToken.RevokedBy,
		&i.ApiToken.RevokeReason,
		&i.ApiToken.CreatedAt,
		&i.ServiceAccountState,
		&i.OwnerUserID,
		&i.ServiceAccountName,
	)
	return i, err
}

const resolveSession = `-- name: ResolveSession :one


SELECT
    s.id, s.user_id, s.token_hash, s.identity_id, s.session_epoch, s.created_at, s.last_seen_at, s.expires_at, s.absolute_expires_at, s.revoked_at, s.ip, s.user_agent, s.mfa_satisfied_at,
    u.state AS user_state,
    u.session_epoch AS user_session_epoch,
    u.username AS username,
    CAST(u.deleted_at IS NOT NULL AS INTEGER) AS user_deleted
FROM session s
JOIN app_user u ON u.id = s.user_id
WHERE s.token_hash = ?
`

type ResolveSessionRow struct {
	Session          Session
	UserState        string
	UserSessionEpoch int64
	Username         string
	UserDeleted      int64
}

// ResolveSession is the cookie half of the auth path: one lookup on ux_session_token, joined to the
// user because every session check needs the account's state and its session epoch in the same
// round trip.
//
// THE EPOCH COMPARISON IS THE CALLER'S. Both epochs come back and internal/auth requires them equal,
// which is what makes "sign out everywhere" one UPDATE on the user row rather than an UPDATE over
// every session. Doing the comparison in SQL would turn a bumped epoch into "no such session", and
// the log line that says a session was killed by an epoch bump is the one that explains a mass
// logout to the officer who caused it.
// THE SESSION ROW ARRIVES WHOLE, through sqlc.embed, and the user's four columns arrive beside it.
// That is not a style preference: sqlc's SQLite engine loses a column's nullability across a JOIN
// and types every nullable one as interface{}, which AGENTS.md bans in a domain signature and which
// would put a runtime type assertion on the auth hot path. Embedding hands back the generated
// Session model, whose nullable columns are already *int64 under emit_pointers_for_null_types.
//
// user_deleted is a PREDICATE rather than the timestamp, for the same reason: the resolver only asks
// whether the account is gone, and a boolean expression is a column sqlc types without help.
func (q *Queries) ResolveSession(ctx context.Context, tokenHash []byte) (ResolveSessionRow, error) {
	row := q.db.QueryRowContext(ctx, resolveSession, tokenHash)
	var i ResolveSessionRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.IdentityID,
		&i.Session.SessionEpoch,
		&i.Session.CreatedAt,
		&i.Session.LastSeenAt,
		&i.Session.ExpiresAt,
		&i.Session.AbsoluteExpiresAt,
		&i.Session.RevokedAt,
		&i.Session.Ip,
		&i.Session.UserAgent,
		&i.Session.MfaSatisfiedAt,
		&i.UserState,
		&i.UserSessionEpoch,
		&i.Username,
		&i.UserDeleted,
	)
	return i, err
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec

UPDATE api_token
SET revoked_at    = CAST(?1 AS INTEGER),
    revoked_by    = ?2,
    revoke_reason = ?3
WHERE id = ?4 AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	RevokedAt    int64
	RevokedBy    *string
	RevokeReason string
	ID           string
}

// RevokeAPIToken kills one token immediately - the property ADR-0011 chose opaque tokens over JWTs
// to get. The reason is recorded because a revocation without one is a support conversation six
// months later; revoked_by is a user id, or NULL when the binary itself did it (a leaked-token sweep,
// an import). The `revoked_at IS NULL` guard keeps the first instant, as RevokeSession's does.
func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeAPIToken,
		arg.RevokedAt,
		arg.RevokedBy,
		arg.RevokeReason,
		arg.ID,
	)
	return err
}

const revokeSession = `-- name: RevokeSession :exec

UPDATE session
SET revoked_at = CAST(?1 AS INTEGER)
WHERE id = ?2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	RevokedAt int64
	ID        string
}

// RevokeSession ends one session immediately. The `revoked_at IS NULL` guard keeps the FIRST
// instant: when a session was revoked is the interesting fact, and a repeated call - a retry, a
// second click on "sign out this device" - must not rewrite it.
func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.RevokedAt, arg.ID)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec

UPDATE api_token
SET last_used_at = CAST(?1 AS INTEGER)
WHERE id = ?2
  AND (last_used_at IS NULL OR last_used_at < CAST(?3 AS INTEGER))
`

type TouchAPITokenParams struct {
	Now         int64
	ID          string
	TouchBefore int64
}

// TouchAPIToken records that a token was used, throttled and guarded exactly as TouchSession is.
//
// last_used_ip IS NOT WRITTEN HERE. Behind the reverse proxy this project recommends every request
// arrives from 127.0.0.1, and there is no DKP_TRUSTED_PROXIES yet (issue #98), so the only address
// available is either useless or attacker-controlled. A column that says ” is honest; one that says
// whatever X-Forwarded-For claimed is a lie in the screen an officer reads after a leak.
func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, arg.Now, arg.ID, arg.TouchBefore)
	return err
}

const touchSession = `-- name: TouchSession :exec


UPDATE session
SET last_seen_at = CAST(?1 AS INTEGER),
    expires_at   = min(CAST(?2 AS INTEGER), absolute_expires_at)
WHERE id = ?3
  AND last_seen_at < CAST(?4 AS INTEGER)
`

type TouchSessionParams struct {
	Now           int64
	IdleExpiresAt int64
	ID            string
	TouchBefore   int64
}

// TouchSession advances last_seen_at and slides the idle expiry, both THROTTLED by the caller and
// guarded here.
//
// THE GUARD IS WHAT MAKES IT SAFE TO CALL, not an optimisation: `last_seen_at < ?` means a burst of
// concurrent requests on one session produces at most one write, on SQLite's single writer, which is
// the connection raid-night awards are queued on. internal/auth calls this only when the stored
// value is already older than its throttle interval, so the common case is no statement at all.
//
// expires_at NEVER PASSES absolute_expires_at. The idle window slides on use (14 days, 30 with
// "remember me"); the absolute ceiling does not, so a session held open by a polling script still
// ends. min() is SQLite's two-argument scalar minimum, not the aggregate.
// THE CASTS ARE LOAD-BEARING, not noise. sqlc's SQLite engine takes a parameter's Go type from the
// expression it lands in: inside min() it has no column affinity to read and emits interface{}, and
// compared against a nullable column it emits *int64. Both are Micros, both are NOT NULL here, and
// `any` in a domain signature is what .claude/rules/go-idioms.md bans - so each one is pinned in the
// QUERY, the way BalanceAsOfSeq's aggregate is, because a sqlc.yaml override keys on table.column
// and a parameter inside an expression has neither.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession,
		arg.Now,
		arg.IdleExpiresAt,
		arg.ID,
		arg.TouchBefore,
	)
	return err
}
