// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authz.sql

package sqlitegen

import (
	"context"
)

const getPermission = `-- name: GetPermission :one
SELECT
    key, category, label, description, is_dangerous, requires_step_up,
    orphaned_at, sort_order
FROM permission
WHERE key = ?
`

func (q *Queries) GetPermission(ctx context.Context, key string) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermission, key)
	var i Permission
	err := row.Scan(
		&i.Key,
		&i.Category,
		&i.Label,
		&i.Description,
		&i.IsDangerous,
		&i.RequiresStepUp,
		&i.OrphanedAt,
		&i.SortOrder,
	)
	return i, err
}

const insertRole = `-- name: InsertRole :exec

INSERT INTO role (
    id, key, name, name_norm, description, is_builtin, applies_to, sort_order,
    deleted_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, ?)
`

type InsertRoleParams struct {
	ID          string
	Key         *string
	Name        string
	NameNorm    string
	Description string
	IsBuiltin   int64
	AppliesTo   string
	SortOrder   int64
	CreatedAt   int64
	UpdatedAt   int64
}

// InsertRole writes one role. The seed calls it inside the same transaction that upserts the
// permission rows, because role_permission references permission(key) and the grants below would
// otherwise fail the foreign key on a fresh install - which is also why the seed cannot live in the
// migration beside pool and account: at migration time the permission table is empty.
func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) error {
	_, err := q.db.ExecContext(ctx, insertRole,
		arg.ID,
		arg.Key,
		arg.Name,
		arg.NameNorm,
		arg.Description,
		arg.IsBuiltin,
		arg.AppliesTo,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertRolePermission = `-- name: InsertRolePermission :exec
INSERT INTO role_permission (role_id, permission_key) VALUES (?, ?)
`

type InsertRolePermissionParams struct {
	RoleID        string
	PermissionKey string
}

func (q *Queries) InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, insertRolePermission, arg.RoleID, arg.PermissionKey)
	return err
}

const listPermissions = `-- name: ListPermissions :many

SELECT
    key, category, label, description, is_dangerous, requires_step_up,
    orphaned_at, sort_order
FROM permission
ORDER BY sort_order, key
`

// Permission catalogue reconciliation - the boot path that projects internal/authz/catalogue.go
// into the permission table (canonical section 6, docs/design/01-domain-model.md section 5).
//
// Shapes follow db/RECIPES.md. Every statement that reaches SQLite in this project is generated
// from a file like this one: db.Query and db.Exec outside internal/store are grep-banned (gate
// SQL002), so the only way a new query enters the codebase is by being written here first and
// reviewed as SQL.
//
// FOUR STATEMENTS AND NO "DELETE FROM permission". That is the whole design of the reconciliation
// and not an omission: role_permission is FK-constrained to permission(key), so deleting a key a
// newer binary stopped shipping would either fail against the grants that reference it or - with a
// cascade - silently strip capability from every role that held it, permanently, on a DOWNGRADE.
// OrphanPermission stamps the row instead, UpsertPermission clears the stamp when the key comes
// back, and no code path in this product removes a permission row.
//
// THE SET IS SMALL AND THE WHOLE-TABLE READ IS DELIBERATE. There are fifty-eight keys, read once per
// boot, so ListPermissions returns every row and the diff against the catalogue happens in Go where
// it can be unit-tested. A sqlc.slice() over the catalogue would move that set logic into SQL for no
// measurable gain on a table this size.
//
// Keep this comment ASCII-only. sqlc v1.31.1 computes each query's text span in bytes but truncates
// by rune count, so a multibyte character (an em dash, a section sign) in a preceding comment lops
// that many trailing characters off the generated query string. The failure is silent at generate
// time and shows up as a syntax error only when the query runs.
func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.Key,
			&i.Category,
			&i.Label,
			&i.Description,
			&i.IsDangerous,
			&i.RequiresStepUp,
			&i.OrphanedAt,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many

SELECT
    id, key, name, name_norm, description, is_builtin, applies_to, sort_order,
    deleted_at, created_at, updated_at
FROM role
ORDER BY sort_order, id
`

// Built-in roles (docs/design/01-domain-model.md section 5.1). SEEDED, not reconciled - the domain
// model calls this table "the seed, not a second catalogue", and the distinction is a control rather
// than a wording choice: rewriting a built-in role's grants on every boot would silently restore a
// permission an officer deliberately revoked, which is a security decision being undone by a restart.
// So internal/authz seeds a built-in role and its grants only when the role row is absent.
//
// There is no UPDATE and no DELETE here. A built-in role is not renamable and not deletable; the role
// editor changes grants, which is role_permission's business and lands with it.
func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.NameNorm,
			&i.Description,
			&i.IsBuiltin,
			&i.AppliesTo,
			&i.SortOrder,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orphanPermission = `-- name: OrphanPermission :exec

UPDATE permission
SET orphaned_at = ?
WHERE key = ? AND orphaned_at IS NULL
`

type OrphanPermissionParams struct {
	OrphanedAt *int64
	Key        string
}

// OrphanPermission marks a key the running binary no longer ships. The `orphaned_at IS NULL` guard
// makes it idempotent and keeps the FIRST timestamp: the interesting fact is when the key stopped
// being shipped, not when the instance was last restarted, and every boot after a downgrade would
// otherwise rewrite it.
func (q *Queries) OrphanPermission(ctx context.Context, arg OrphanPermissionParams) error {
	_, err := q.db.ExecContext(ctx, orphanPermission, arg.OrphanedAt, arg.Key)
	return err
}

const upsertPermission = `-- name: UpsertPermission :exec

INSERT INTO permission (
    key, category, label, description, is_dangerous, requires_step_up,
    orphaned_at, sort_order
) VALUES (?, ?, ?, ?, ?, ?, NULL, ?)
ON CONFLICT (key) DO UPDATE SET
    category         = excluded.category,
    label            = excluded.label,
    description      = excluded.description,
    is_dangerous     = excluded.is_dangerous,
    requires_step_up = excluded.requires_step_up,
    orphaned_at      = NULL,
    sort_order       = excluded.sort_order
`

type UpsertPermissionParams struct {
	Key            string
	Category       string
	Label          string
	Description    string
	IsDangerous    int64
	RequiresStepUp int64
	SortOrder      int64
}

// UpsertPermission writes one catalogue row. It ALWAYS clears orphaned_at: reaching this statement
// means the running binary ships the key, which is exactly the condition orphaned_at records the
// absence of, so an upgrade that restores a key restores its row to live in the same statement that
// refreshes its label.
func (q *Queries) UpsertPermission(ctx context.Context, arg UpsertPermissionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPermission,
		arg.Key,
		arg.Category,
		arg.Label,
		arg.Description,
		arg.IsDangerous,
		arg.RequiresStepUp,
		arg.SortOrder,
	)
	return err
}
