// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meta.sql

package sqlitegen

import (
	"context"
)

const getMetaValue = `-- name: GetMetaValue :one

SELECT value FROM dkp_meta WHERE key = ?
`

// Instance state in dkp_meta. Shapes follow db/RECIPES.md.
//
// Every statement that reaches SQLite in this project is generated from a file like this one.
// `db.Query` and `db.Exec` outside internal/store are grep-banned (gate SQL002), so the only way
// a new query enters the codebase is by being written here first and reviewed as SQL.
func (q *Queries) GetMetaValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMetaValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertMetaValue = `-- name: UpsertMetaValue :exec
INSERT INTO dkp_meta (key, value, updated_at)
VALUES (?, ?, ?)
ON CONFLICT (key) DO UPDATE SET
    value      = excluded.value,
    updated_at = excluded.updated_at
`

type UpsertMetaValueParams struct {
	Key       string
	Value     string
	UpdatedAt int64
}

func (q *Queries) UpsertMetaValue(ctx context.Context, arg UpsertMetaValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertMetaValue, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
