// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

type Account struct {
	ID        string
	Kind      string
	PersonID  *string
	SystemKey *string
	Label     string
	CreatedAt int64
	UpdatedAt int64
}

type AuditLog struct {
	ID            string
	Seq           int64
	At            int64
	ActorKind     string
	ActorLabel    string
	Action        string
	ResourceKind  string
	ResourceID    *string
	Outcome       string
	LedgerBatchID *string
	PrevHash      []byte
	Hash          []byte
}

type BalanceSnapshot struct {
	PoolID      string
	AccountID   string
	BalanceKind string
	AmountCp    int64
	AsOfSeq     int64
	EntryCount  int64
	UpdatedAt   int64
}

type DecayRun struct {
	ID                 string
	PoolID             string
	Kind               string
	CadencePeriod      string
	ScheduledForAt     int64
	ExecutedAt         *int64
	State              string
	DryRunResultJson   string
	ConfigSnapshotJson string
	LedgerBatchID      *string
	TriggeredBy        *string
	Error              string
	CreatedAt          int64
	UpdatedAt          int64
}

type DkpMetum struct {
	Key       string
	Value     string
	UpdatedAt int64
}

type EventOutbox struct {
	EventSeq    int64
	ID          string
	Topic       string
	EventType   string
	ResourceRef string
	CreatedAt   int64
}

type Guild struct {
	ID                int64
	Name              string
	Tag               string
	Timezone          string
	WeekStart         int64
	PointsLabel       string
	PointsPrecision   int64
	InactiveAfterDays *int64
	AutoSetInactive   int64
	HideInactive      int64
	CreatedAt         int64
	UpdatedAt         int64
}

type LedgerBatch struct {
	ID                 string
	PoolID             string
	Seq                int64
	Kind               string
	StrategyID         string
	StrategyVersion    string
	ConfigSnapshotJson string
	RngSeed            *int64
	Source             string
	SourceRef          *string
	ActorUserID        *string
	ActorTokenID       *string
	ActorIsBeneficiary int64
	Reason             string
	ReversesBatchID    *string
	EffectiveAt        int64
	RecordedAt         int64
	EffectiveDay       string
	IdempotencyKey     *string
	EntryCount         int64
	NetAmountCp        int64
	PrevHash           []byte
	Hash               []byte
}

type LedgerEntry struct {
	ID           string
	BatchID      string
	PoolID       string
	Seq          int64
	AccountID    string
	CharacterID  *string
	BalanceKind  string
	AmountCp     int64
	ItemID       *string
	ItemAwardID  *string
	RaidID       *string
	TickID       *string
	MetadataJson string
}

type Permission struct {
	Key            string
	Category       string
	Label          string
	Description    string
	IsDangerous    int64
	RequiresStepUp int64
	OrphanedAt     *int64
	SortOrder      int64
}

type Pool struct {
	ID                 string
	Name               string
	NameNorm           string
	StrategyID         string
	StrategyVersion    string
	BalanceKinds       string
	CreatedAt          int64
	UpdatedAt          int64
	StrategyConfigJson string
	EarnStrategyID     string
	EarnConfigJson     string
	SpendStrategyID    string
	SpendConfigJson    string
	OverTimeStrategyID string
	OverTimeConfigJson string
}

type PoolConfigChange struct {
	ID                  string
	PoolID              string
	ChangedAt           int64
	ChangedBy           *string
	FromStrategyID      string
	FromStrategyVersion string
	FromConfigJson      string
	ToStrategyID        string
	ToStrategyVersion   string
	ToConfigJson        string
	Reason              string
	MigrationBatchID    *string
}

type Role struct {
	ID          string
	Key         *string
	Name        string
	NameNorm    string
	Description string
	IsBuiltin   int64
	AppliesTo   string
	SortOrder   int64
	DeletedAt   *int64
	CreatedAt   int64
	UpdatedAt   int64
}

type RoleAssignment struct {
	ID               string
	SubjectKind      string
	SubjectID        string
	RoleID           string
	ScopeType        string
	ScopeID          *string
	SuspendedUntilAt *int64
	GrantedBy        *string
	GrantedVia       string
	ExpiresAt        *int64
	CreatedAt        int64
	UpdatedAt        int64
}

type RolePermission struct {
	RoleID        string
	PermissionKey string
}
