// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

type DkpMetum struct {
	Key       string
	Value     string
	UpdatedAt int64
}

type Guild struct {
	ID                int64
	Name              string
	Tag               string
	Timezone          string
	WeekStart         int64
	PointsLabel       string
	PointsPrecision   int64
	InactiveAfterDays *int64
	AutoSetInactive   int64
	HideInactive      int64
	CreatedAt         int64
	UpdatedAt         int64
}
