// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlitegen

import (
	"context"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :one


INSERT INTO event_outbox (id, topic, event_type, resource_ref, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING event_seq
`

type InsertOutboxEventParams struct {
	ID          string
	Topic       string
	EventType   string
	ResourceRef string
	CreatedAt   int64
}

// Event outbox - the global event sequence behind SSE, webhooks and Last-Event-ID. Phase 0 PR 10a.
//
// Shapes follow db/RECIPES.md. Every statement that reaches SQLite in this project is generated from
// a file like this one: db.Query and db.Exec outside internal/store are grep-banned (gate SQL002),
// so the only way a new query enters the codebase is by being written here first and reviewed as SQL.
//
// WRITE-ONLY at this phase. The tailer that reads ix_outbox_topic and feeds SSE frames is Phase 1
// (the realtime lane); what ships now is the insert a committing transaction makes, so that no state
// change can ever exist without its event and no event can exist for a change that rolled back.
//
// Keep every comment in this file ASCII-only. sqlc v1.31.1 computes each query's text span in bytes
// but truncates by rune count, so a multibyte character in a preceding comment lops that many
// trailing characters off the generated query string - silent at generate time, a syntax error at
// run time.
// InsertOutboxEvent appends one event and RETURNS the sequence the database allocated.
//
// event_seq is INTEGER PRIMARY KEY AUTOINCREMENT, so SQLite allocates it and never reuses a number
// that has been used before - which is what keeps Last-Event-ID replay sound across a prune. RETURNING
// reads it back in the same statement: the alternative, last_insert_rowid(), is a second round trip
// whose answer depends on nothing else having written on this connection in between, and "nothing
// else wrote in between" is a property nobody should have to reason about to learn a row's own id.
//
// This is the third sequence in the product and it answers a different question from the other two.
// ledger_batch.seq is per-pool and orders a balance; audit_log.seq is instance-wide and gapless and
// orders the audit chain; event_seq is instance-wide, never-reused and orders the event stream. A
// bot author who confuses them gets wrong answers silently, which is why they do not share a name.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertOutboxEvent,
		arg.ID,
		arg.Topic,
		arg.EventType,
		arg.ResourceRef,
		arg.CreatedAt,
	)
	var event_seq int64
	err := row.Scan(&event_seq)
	return event_seq, err
}
