// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

import (
	"context"
)

type Querier interface {
	// Instance state in dkp_meta. Shapes follow db/RECIPES.md.
	//
	// Every statement that reaches SQLite in this project is generated from a file like this one.
	// `db.Query` and `db.Exec` outside internal/store are grep-banned (gate SQL002), so the only way
	// a new query enters the codebase is by being written here first and reviewed as SQL.
	GetMetaValue(ctx context.Context, key string) (string, error)
	UpsertMetaValue(ctx context.Context, arg UpsertMetaValueParams) error
}

var _ Querier = (*Queries)(nil)
